language: node_js
node_js:
- '8'
before_script: npm install
before_install:
  - openssl aes-256-cbc -K $encrypted_d98ac1bdb521_key -iv $encrypted_d98ac1bdb521_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 118.24.89.72\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh ubuntu@118.24.89.72 'cd /var/www/workspace/chat && git pull'


